export type SchoolInfo = {
  region: string;
  valle: string;
  municipio: string;
  subsistema: string;
  control: string;
  nivel: string;
  servicioEducativo: string;
  cct: string;
  turno: string;
  nombre: string;
  domicilio: string;
  localidad: string;
  telefono: string;
  zonaEscolar: string;
  sector: string;
  director: string;
  hombres: number;
  mujeres: number;
  alumnos: number;
  grupos: number;
  maestros: number;
  administrativos: number;
  aulasExistentes: number;
  aulasEnUso: number;
  modalidad: string;
  dsr?: string;
};

export const schoolsDirectory: SchoolInfo[] = [
  // AMECAMECA
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AMECAMECA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0065B', turno: 'MATUTINO', nombre: 'DR. MANUEL SANDOVAL VALLARTA', domicilio: 'CALLE XICOTENCATL', localidad: 'AMECAMECA DE JUAREZ', telefono: '5979780731', zonaEscolar: '23', sector: '9', director: 'HECTOR LEYVA ZETINA', hombres: 270, mujeres: 287, alumnos: 557, grupos: 18, maestros: 23, administrativos: 19, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AMECAMECA', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES0127C', turno: 'MATUTINO', nombre: 'CENTRO ESCOLAR MEXICO', domicilio: 'CALLE XICOTENCATL 58', localidad: 'AMECAMECA DE JUAREZ', telefono: '5979785018', zonaEscolar: '23', sector: '9', director: 'LAURA GUADALUPE RUIZ ROMERO', hombres: 18, mujeres: 16, alumnos: 34, grupos: 3, maestros: 8, administrativos: 1, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AMECAMECA', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1363M', turno: 'MATUTINO', nombre: 'COLEGIO REAL CHAPULTEPEC', domicilio: 'AVENIDA CHAPULTEPEC 7', localidad: 'AMECAMECA DE JUAREZ', telefono: '5544645461', zonaEscolar: '23', sector: '9', director: 'AZUCENA AIDE PAEZ AGUILAR', hombres: 51, mujeres: 42, alumnos: 93, grupos: 6, maestros: 13, administrativos: 3, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AMECAMECA', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1440A', turno: 'MATUTINO', nombre: 'COLEGIO HILLS', domicilio: 'CALLE CRUZ VERDE', localidad: 'AMECAMECA DE JUAREZ', telefono: '5519119564', zonaEscolar: '23', sector: '9', director: 'LAURA ELVIRA ELVIRA ARMAS', hombres: 41, mujeres: 44, alumnos: 85, grupos: 3, maestros: 11, administrativos: 2, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AMECAMECA', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA PARTICULAR', cct: '15PST0601I', turno: 'MATUTINO', nombre: 'DANEI', domicilio: 'CALLE GUADALUPE VICTORIA 235', localidad: 'AMECAMECA DE JUAREZ', telefono: '5979780123', zonaEscolar: '23', sector: '8', director: 'MA.DELCARMEN SALAZAR HERNANDEZ', hombres: 56, mujeres: 63, alumnos: 119, grupos: 5, maestros: 11, administrativos: 4, aulasExistentes: 7, aulasEnUso: 5, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'ATLAUTLA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0109I', turno: 'MATUTINO', nombre: 'NARCISO MENDOZA (EL NIÑO ARTILLERO)', domicilio: 'AVENIDA MEXICO 1', localidad: 'SAN JUAN TEPECOCULCO', telefono: '5971013237', zonaEscolar: '23', sector: '9', director: 'HIRAM ULISES LOPEZ HERNANDEZ', hombres: 125, mujeres: 135, alumnos: 260, grupos: 9, maestros: 12, administrativos: 11, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'ATLAUTLA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0082Y', turno: 'MATUTINO', nombre: 'LIC. ALVARO GALVEZ Y FUENTES', domicilio: 'CARRETERA ESTATAL LIBRE, DE ATLAUTLA A OZUMBA, KM. 0', localidad: 'ATLAUTLA DE VICTORIA', telefono: '5979761900', zonaEscolar: '22', sector: '1', director: 'ADRIAN DE LA ROSA NOLASCO', hombres: 124, mujeres: 111, alumnos: 235, grupos: 9, maestros: 9, administrativos: 2, aulasExistentes: 10, aulasEnUso: 9, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'ATLAUTLA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0162J', turno: 'MATUTINO', nombre: 'BENITO JUAREZ', domicilio: 'AVENIDA JUAREZ 91', localidad: 'SAN JUAN TEHUIXTITLAN', telefono: '7353518114', zonaEscolar: '22', sector: '1', director: 'ADRIAN CARLOS ARAGON LOPEZ', hombres: 75, mujeres: 59, alumnos: 134, grupos: 6, maestros: 6, administrativos: 4, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'ATLAUTLA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0374M', turno: 'MATUTINO', nombre: 'IZTACCIHUATL', domicilio: 'CALLE LAS CRUCES', localidad: 'POPO PARK', telefono: '5979767798', zonaEscolar: '22', sector: '1', director: 'GUSTAVO ARTURO BERNAL ARENAS', hombres: 110, mujeres: 89, alumnos: 199, grupos: 7, maestros: 7, administrativos: 5, aulasExistentes: 7, aulasEnUso: 7, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'AYAPANGO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0392B', turno: 'MATUTINO', nombre: 'LAURA MENDEZ DE CUENCA', domicilio: 'AVENIDA NACIONAL', localidad: 'AYAPANGO DE GABRIEL RAMOS M.', telefono: '5979824336', zonaEscolar: '22', sector: '1', director: 'IRMA AVILA RAMOS', hombres: 45, mujeres: 38, alumnos: 83, grupos: 4, maestros: 4, administrativos: 3, aulasExistentes: 5, aulasEnUso: 4, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0038E', turno: 'MATUTINO', nombre: 'MOISES SAENZ', domicilio: 'CALLE GERANIO 2', localidad: 'SAN MATEO TEZOQUIPAN MIRAFLORES', telefono: '5510127066', zonaEscolar: '46', sector: '9', director: 'JONATAN MIGUEL REYES GARCIA', hombres: 220, mujeres: 246, alumnos: 466, grupos: 18, maestros: 29, administrativos: 15, aulasExistentes: 24, aulasEnUso: 18, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0227X', turno: 'MATUTINO', nombre: '15 DE MAYO', domicilio: 'AVENIDA FERROCARRIL', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5517345574', zonaEscolar: '22', sector: '9', director: 'J. FIDEL CELSO CRUZ', hombres: 268, mujeres: 247, alumnos: 515, grupos: 18, maestros: 23, administrativos: 12, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0244N', turno: 'MATUTINO', nombre: 'JUAN ESCUTIA', domicilio: 'AVENIDA EJIDAL 1', localidad: 'SAN MARCOS HUIXTOCO', telefono: '5517222426', zonaEscolar: '22', sector: '9', director: 'CECILIO ARCE PEREZ', hombres: 177, mujeres: 175, alumnos: 352, grupos: 9, maestros: 11, administrativos: 12, aulasExistentes: 12, aulasEnUso: 12, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0298R', turno: 'MATUTINO', nombre: 'NEZAHUALCOYOTL', domicilio: 'CALLE UNION', localidad: 'SAN MATEO HUITZILZINGO', telefono: '2231176404', zonaEscolar: '22', sector: '9', director: 'BERNARDINO JUAN HUERTA DURAN', hombres: 166, mujeres: 155, alumnos: 321, grupos: 9, maestros: 15, administrativos: 9, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0344M', turno: 'MATUTINO', nombre: 'JOSE ANTONIO ALZATE RAMIREZ', domicilio: 'CALLE ZACATECAS S/N', localidad: 'SAN MARTIN CUAUTLALPAN', telefono: '5525867587', zonaEscolar: '46', sector: '9', director: 'CRUZ JUANITA SANCHEZ MORALES', hombres: 225, mujeres: 189, alumnos: 414, grupos: 9, maestros: 14, administrativos: 8, aulasExistentes: 15, aulasEnUso: 9, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0353U', turno: 'MATUTINO', nombre: 'JOAQUIN FERNANDEZ DE LIZARDI', domicilio: 'CERRADA DE LA CAPILLA', localidad: 'SAN MARTIN CUAUTLALPAN', telefono: '7772186050', zonaEscolar: '46', sector: '9', director: 'PAVEL ROSAS RABADAN', hombres: 289, mujeres: 266, alumnos: 555, grupos: 15, maestros: 23, administrativos: 13, aulasExistentes: 15, aulasEnUso: 15, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0358P', turno: 'MATUTINO', nombre: 'LAZARO CARDENAS DEL RIO', domicilio: 'CALLE HUEXOCULCO', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5561176143', zonaEscolar: '46', sector: '9', director: 'RUFINO JAVIER CAMARILLO DURAN', hombres: 322, mujeres: 375, alumnos: 697, grupos: 15, maestros: 21, administrativos: 14, aulasExistentes: 17, aulasEnUso: 15, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0362B', turno: 'MATUTINO', nombre: 'JAIME SABINES', domicilio: 'AVENIDA EX HACIENDA GUADALUPE', localidad: 'LA CANDELARIA TLAPALA', telefono: '5515105098', zonaEscolar: '46', sector: '9', director: 'JUAN LUIS PERALTA MIRELES', hombres: 209, mujeres: 211, alumnos: 420, grupos: 9, maestros: 14, administrativos: 12, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0363A', turno: 'MATUTINO', nombre: 'LEONA VICARIO', domicilio: 'CALLE HACIENDA MIRAFLORES', localidad: 'SAN MARTIN CUAUTLALPAN', telefono: '5554796427', zonaEscolar: '46', sector: '9', director: 'ROBERTO GUZMAN SERRATO', hombres: 268, mujeres: 267, alumnos: 535, grupos: 15, maestros: 27, administrativos: 11, aulasExistentes: 18, aulasEnUso: 15, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0028Q', turno: 'MATUTINO', nombre: 'TELPOCHCALLI', domicilio: 'CALLE ANTIGUO CAMINO A TENANGO', localidad: 'SAN PABLO ATLAZALPAN', telefono: '', zonaEscolar: '23', sector: '8', director: 'ANTONIO VEGA MAYA', hombres: 285, mujeres: 302, alumnos: 587, grupos: 15, maestros: 20, administrativos: 16, aulasExistentes: 15, aulasEnUso: 12, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0142I', turno: 'MATUTINO', nombre: 'MIGUEL ALEMAN', domicilio: 'CALLE GUERRERO', localidad: 'SANTA MARIA HUEXOCULCO', telefono: '5559888359', zonaEscolar: '23', sector: '8', director: 'HUMBERTO HERNANDEZ JUAREZ', hombres: 284, mujeres: 258, alumnos: 542, grupos: 12, maestros: 17, administrativos: 19, aulasExistentes: 12, aulasEnUso: 12, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0241I', turno: 'MATUTINO', nombre: 'JOSE VASCONCELOS CALDERON', domicilio: 'AVENIDA PLAZA MAYOR', localidad: 'SAN MARTIN CUAUTLALPAN', telefono: '5556471217', zonaEscolar: '23', sector: '8', director: 'KARLA MANTEROLA GUTIERREZ', hombres: 256, mujeres: 265, alumnos: 521, grupos: 12, maestros: 19, administrativos: 12, aulasExistentes: 16, aulasEnUso: 12, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0041Y', turno: 'MATUTINO', nombre: 'LAZARO CARDENAS DEL RIO', domicilio: 'CERRADA TIZAPA', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5530920328', zonaEscolar: '2', sector: '1', director: 'JOSE JUAN FLORIN MORENO', hombres: 333, mujeres: 285, alumnos: 618, grupos: 19, maestros: 19, administrativos: 7, aulasExistentes: 19, aulasEnUso: 19, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0156Z', turno: 'MATUTINO', nombre: 'EMILIANO ZAPATA SALAZAR', domicilio: 'CALLE PROLONGACION MANUEL HERNANDEZ 1', localidad: 'LA CANDELARIA TLAPALA', telefono: '5554128938', zonaEscolar: '2', sector: '1', director: 'ADRIAN DE LA ROSA NOLASCO', hombres: 103, mujeres: 95, alumnos: 198, grupos: 6, maestros: 6, administrativos: 2, aulasExistentes: 8, aulasEnUso: 8, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0158X', turno: 'MATUTINO', nombre: 'PLAN DE AYUTLA', domicilio: 'CALLE VICENTE GUERRERO', localidad: 'SAN MATEO HUITZILZINGO', telefono: '5522367040', zonaEscolar: '2', sector: '1', director: 'MARTHA OSEBELI BADILLO JIMENEZ', hombres: 60, mujeres: 28, alumnos: 88, grupos: 3, maestros: 3, administrativos: 2, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0168D', turno: 'MATUTINO', nombre: 'ANTONIO MARIA BUCARELI', domicilio: 'CALLE MORELOS', localidad: 'SAN MARCOS HUIXTOCO', telefono: '5517222739', zonaEscolar: '2', sector: '1', director: 'MARTIN ROCHA GUZMAN', hombres: 42, mujeres: 21, alumnos: 63, grupos: 4, maestros: 4, administrativos: 2, aulasExistentes: 5, aulasEnUso: 4, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0170S', turno: 'MATUTINO', nombre: 'IGNACIO ALLENDE', domicilio: 'AVENIDA PROLONGACIÓN HIDALGO', localidad: 'SAN MATEO HUITZILZINGO', telefono: '5561245563', zonaEscolar: '2', sector: '1', director: 'AMANDA GOMEZ MENDOZA', hombres: 106, mujeres: 79, alumnos: 185, grupos: 9, maestros: 8, administrativos: 3, aulasExistentes: 9, aulasEnUso: 8, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0302T', turno: 'MATUTINO', nombre: 'JUANA DE ASBAJE', domicilio: 'CALLE GENOVEVO DE LA OCA', localidad: 'SAN MATEO TEZOQUIPAN MIRAFLORES', telefono: '2464160617', zonaEscolar: '22', sector: '1', director: 'GILBERTO SALAZAR GARCIA', hombres: 110, mujeres: 95, alumnos: 205, grupos: 8, maestros: 9, administrativos: 3, aulasExistentes: 9, aulasEnUso: 8, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0336J', turno: 'MATUTINO', nombre: 'JOSE VASCONCELOS', domicilio: 'CALLE NTRA. SEÑORA DE LOS ANGELES', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5589592983', zonaEscolar: '2', sector: '1', director: 'MARIA DE LOURDES HERNANDEZ DIAZ', hombres: 87, mujeres: 62, alumnos: 149, grupos: 6, maestros: 6, administrativos: 4, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0342U', turno: 'MATUTINO', nombre: 'CUAUHTEMOC', domicilio: 'CALLE JUAN FERNÁNDEZ ALBARRAN', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5517170544', zonaEscolar: '2', sector: '1', director: 'JACINTO ROMAN MONTES', hombres: 42, mujeres: 27, alumnos: 69, grupos: 3, maestros: 3, administrativos: 2, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES0136K', turno: 'MATUTINO', nombre: 'LICEO EDUCATIVO DAVID PAUL AUSUBEL', domicilio: 'CALLE PALMA 738', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5530924918', zonaEscolar: '22', sector: '9', director: 'MONICA ITZEL LOPEZ CORTES', hombres: 14, mujeres: 14, alumnos: 28, grupos: 3, maestros: 7, administrativos: 2, aulasExistentes: 6, aulasEnUso: 4, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES0508K', turno: 'MATUTINO', nombre: 'JUANA DE ASBAJE', domicilio: 'CALLE PORVENIR 321', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5575854917', zonaEscolar: '22', sector: '9', director: 'AMELIA VILLANUEVA CONTRERAS', hombres: 119, mujeres: 118, alumnos: 237, grupos: 9, maestros: 18, administrativos: 8, aulasExistentes: 15, aulasEnUso: 10, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1373T', turno: 'MATUTINO', nombre: 'SOR JUANA INES DE LA CRUZ', domicilio: 'CALLEJÓN DE LA PAZ', localidad: 'SAN MATEO TEZOQUIPAN MIRAFLORES', telefono: '5531997985', zonaEscolar: '46', sector: '9', director: 'ALAN JOVANY PALACIOS BOTELLO', hombres: 92, mujeres: 90, alumnos: 182, grupos: 6, maestros: 10, administrativos: 2, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1446V', turno: 'MATUTINO', nombre: 'COLEGIO YOLIZTLI', domicilio: 'AVENIDA MORELOS NORTE 500', localidad: 'SAN GREGORIO CUAUTZINGO', telefono: '5569601994', zonaEscolar: '46', sector: '9', director: 'XOCHITL VERONICA GAZCA SANCHEZ', hombres: 62, mujeres: 55, alumnos: 117, grupos: 4, maestros: 11, administrativos: 6, aulasExistentes: 4, aulasEnUso: 4, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1464K', turno: 'MATUTINO', nombre: 'COLEGIO HOWARD GARDNER', domicilio: 'CALLE LIBERTAD MANZANA 1, LOTE1', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5559774526', zonaEscolar: '22', sector: '9', director: 'YULISA FLORES ANGEL', hombres: 24, mujeres: 19, alumnos: 43, grupos: 3, maestros: 7, administrativos: 3, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA PARTICULAR', cct: '15PST0009G', turno: 'MATUTINO', nombre: 'COLEGIO LEONA VICARIO', domicilio: 'AVENIDA NACIONAL PONIENTE 700', localidad: 'SAN MARTIN CUAUTLALPAN', telefono: '', zonaEscolar: '23', sector: '8', director: 'MA. DE LA LUZ GUTIERREZ ELIZALDE', hombres: 23, mujeres: 36, alumnos: 59, grupos: 3, maestros: 8, administrativos: 2, aulasExistentes: 6, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'CHALCO', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA PARTICULAR', cct: '15PST0602H', turno: 'MATUTINO', nombre: 'VILLA DE LOS NIÑOS', domicilio: 'CARRETERA MUNICIPAL LIBRE, DE CHALCO A MIXQUIC, KM. 2.5', localidad: 'CHALCO DE DIAZ COVARRUBIAS', telefono: '5559751819', zonaEscolar: '23', sector: '8', director: 'REYEZ CRUZ PALMA', hombres: 0, mujeres: 2189, alumnos: 2189, grupos: 42, maestros: 58, administrativos: 4, aulasExistentes: 42, aulasEnUso: 42, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'ECATZINGO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0079K', turno: 'MATUTINO', nombre: 'CUAUHTEMOC', domicilio: 'AVENIDA 5 DE FEBRERO', localidad: 'ECATZINGO DE HIDALGO', telefono: '5971091495', zonaEscolar: '22', sector: '1', director: 'ALFREDO SOSA RUIZ', hombres: 105, mujeres: 72, alumnos: 177, grupos: 9, maestros: 8, administrativos: 1, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'JUCHITEPEC', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0021X', turno: 'MATUTINO', nombre: 'DR. JORGE JIMENEZ CANTU', domicilio: 'AVENIDA MORELOS PONIENTE 439', localidad: 'JUCHITEPEC DE MARIANO RIVAPALACIO', telefono: '5979770218', zonaEscolar: '23', sector: '8', director: 'JAIME FIGUEROA MERCADO', hombres: 288, mujeres: 267, alumnos: 555, grupos: 15, maestros: 23, administrativos: 23, aulasExistentes: 16, aulasEnUso: 15, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'OZUMBA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0303S', turno: 'MATUTINO', nombre: 'JUSTO SIERRA', domicilio: 'CALLE REFORMA 11', localidad: 'COLONIA GUADALUPE HIDALGO', telefono: '5971007330', zonaEscolar: '22', sector: '1', director: 'MARTHA AURORA VERGARA BATALLA', hombres: 33, mujeres: 22, alumnos: 55, grupos: 3, maestros: 3, administrativos: 1, aulasExistentes: 4, aulasEnUso: 3, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'OZUMBA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0337I', turno: 'MATUTINO', nombre: 'OCTAVIO PAZ', domicilio: 'CALLE AHUEHUETE', localidad: 'SAN MATEO TECALCO', telefono: '5979764329', zonaEscolar: '22', sector: '1', director: 'DOMITILA LEAÑOZ MARQUEZ', hombres: 94, mujeres: 65, alumnos: 159, grupos: 7, maestros: 7, administrativos: 1, aulasExistentes: 8, aulasEnUso: 7, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'OZUMBA', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1458Z', turno: 'MATUTINO', nombre: 'COLEGIO ALZATE', domicilio: 'CALLE ALZATE', localidad: 'OZUMBA DE ALZATE', telefono: '5550503466', zonaEscolar: '23', sector: '9', director: 'DIANA ABIGAIL GUERRA DIAZ', hombres: 49, mujeres: 52, alumnos: 101, grupos: 3, maestros: 9, administrativos: 2, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TEMAMATLA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0075A', turno: 'MATUTINO', nombre: 'JOSE MARIA PINO SUAREZ', domicilio: 'AVENIDA GUERRERO 56', localidad: 'TEMAMATLA', telefono: '5559429470', zonaEscolar: '23', sector: '8', director: 'SERGIO VILLEGAS RUIZ', hombres: 275, mujeres: 275, alumnos: 550, grupos: 15, maestros: 20, administrativos: 12, aulasExistentes: 15, aulasEnUso: 15, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TENANGO DEL AIRE', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0369A', turno: 'MATUTINO', nombre: 'GUILLERMO GONZALEZ CAMARENA', domicilio: 'CALLE LA LOMA', localidad: 'SAN JUAN COXTOCAN', telefono: '5971070024', zonaEscolar: '22', sector: '1', director: 'GUILLERMO SILVANO LOPEZ CERECERO', hombres: 35, mujeres: 35, alumnos: 70, grupos: 3, maestros: 3, administrativos: 2, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TEPETLIXPA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0256S', turno: 'MATUTINO', nombre: 'JUANA DE ASBAJE Y RAMIREZ', domicilio: 'CALLE ENRIQUE CARNIADO PERALTA', localidad: 'NEPANTLA DE SOR JUANA INES DE LA CRUZ', telefono: '5979773521', zonaEscolar: '23', sector: '9', director: 'ARTURO SALGADO ESCOBAR', hombres: 62, mujeres: 63, alumnos: 125, grupos: 6, maestros: 11, administrativos: 13, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TEPETLIXPA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0014N', turno: 'MATUTINO', nombre: 'EMILIANO ZAPATA SALAZAR', domicilio: 'CALLE DEL ESTUDIANTE', localidad: 'TEPETLIXPA', telefono: '5979750958', zonaEscolar: '23', sector: '8', director: 'VICTOR MANUEL SEGURA REYES', hombres: 252, mujeres: 217, alumnos: 469, grupos: 14, maestros: 20, administrativos: 22, aulasExistentes: 14, aulasEnUso: 14, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TLALMANALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0004O', turno: 'MATUTINO', nombre: 'J. ENCARNACION F. CORDOBA', domicilio: 'CALLE SUR 2 20', localidad: 'SAN RAFAEL', telefono: '5979759679', zonaEscolar: '23', sector: '9', director: 'JUANA GABRIELA CRUZ TIRZO', hombres: 240, mujeres: 279, alumnos: 519, grupos: 18, maestros: 24, administrativos: 15, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'TLALMANALCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0040Z', turno: 'MATUTINO', nombre: 'FRANCISCO VILLA', domicilio: 'CALLE 5 DE MAYO', localidad: 'TLALMANALCO DE VELAZQUEZ', telefono: '7352499474', zonaEscolar: '22', sector: '1', director: 'FERNANDO GALICIA LOPEZ', hombres: 88, mujeres: 79, alumnos: 167, grupos: 6, maestros: 6, administrativos: 3, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0119P', turno: 'MATUTINO', nombre: 'MIGUEL DE CERVANTES SAAVEDRA', domicilio: 'PROLONGACIÓN EJE 10 SUR', localidad: 'XICO', telefono: '5543390236', zonaEscolar: '22', sector: '9', director: 'JOSE ISRAEL PADILLA COLIN', hombres: 301, mujeres: 314, alumnos: 615, grupos: 18, maestros: 29, administrativos: 15, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0011Q', turno: 'MATUTINO', nombre: 'JOSE ANTONIO DE ALZATE', domicilio: 'CALLE KILOMETRO 24 AUTOPISTA MÉXICO PUEBLA', localidad: 'XICO', telefono: '5516431790', zonaEscolar: '22', sector: '8', director: 'DANIEL PACHECO MORALES', hombres: 349, mujeres: 336, alumnos: 685, grupos: 18, maestros: 17, administrativos: 20, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0116K', turno: 'MATUTINO', nombre: 'REVOLUCION MEXICANA', domicilio: 'AVENIDA SEBASTIAN LERDO DE TEJADA', localidad: 'XICO', telefono: '5513618143', zonaEscolar: '22', sector: '8', director: 'MARYCARMEN REYES PLATA', hombres: 388, mujeres: 414, alumnos: 802, grupos: 18, maestros: 25, administrativos: 21, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0117J', turno: 'MATUTINO', nombre: 'ANAHUACALLI', domicilio: 'AVENIDA ISIDRO FABELA', localidad: 'XICO', telefono: '5594352021', zonaEscolar: '23', sector: '8', director: 'BARBARA MIREYA RAMON REYES', hombres: 375, mujeres: 345, alumnos: 720, grupos: 18, maestros: 26, administrativos: 17, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0118I', turno: 'MATUTINO', nombre: 'LAURA MENDEZ DE CUENCA', domicilio: 'CALLE LEONA VICARIO', localidad: 'XICO', telefono: '5559713130', zonaEscolar: '22', sector: '8', director: 'SERGIO MANUEL SAN CRISTOBAL CABRERA', hombres: 392, mujeres: 420, alumnos: 812, grupos: 18, maestros: 25, administrativos: 26, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0128P', turno: 'MATUTINO', nombre: 'JUAN RULFO', domicilio: 'AVENIDA ADOLFO LÓPEZ MATEOS', localidad: 'XICO', telefono: '5575956296', zonaEscolar: '23', sector: '8', director: 'SILVIA CARPIO ZENTENO', hombres: 383, mujeres: 444, alumnos: 827, grupos: 18, maestros: 23, administrativos: 21, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0061L', turno: 'MATUTINO', nombre: 'CONSTITUCION DE 1917', domicilio: 'CALLE NORTE 37', localidad: 'XICO', telefono: '', zonaEscolar: '21', sector: '1', director: 'HECTOR XXX PACHECO', hombres: 52, mujeres: 42, alumnos: 94, grupos: 5, maestros: 5, administrativos: 4, aulasExistentes: 6, aulasEnUso: 5, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0095B', turno: 'MATUTINO', nombre: 'ALVARO GALVEZ Y FUENTES', domicilio: 'CALLE AGRICULTURA 9', localidad: 'XICO', telefono: '5513143391', zonaEscolar: '21', sector: '1', director: 'DOMITILA LEAÑOS MARQUEZ', hombres: 129, mujeres: 94, alumnos: 223, grupos: 11, maestros: 11, administrativos: 5, aulasExistentes: 11, aulasEnUso: 11, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'TELESECUNDARIA', cct: '15DTV0225E', turno: 'MATUTINO', nombre: 'GUSTAVO BAZ PRADA', domicilio: 'CALLE SUR 23', localidad: 'XICO', telefono: '', zonaEscolar: '2', sector: '1', director: 'HORTENSIA LOPEZ VELASCO', hombres: 81, mujeres: 85, alumnos: 166, grupos: 9, maestros: 9, administrativos: 6, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DTV', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1343Z', turno: 'MATUTINO', nombre: 'COLEGIO EDUCACION Y PATRIA', domicilio: 'CALLE JOSÉ MARÍA IGLESIAS 30', localidad: 'XICO', telefono: '5560924840', zonaEscolar: '22', sector: '9', director: 'GUSTAVO MARTINEZ MARTINEZ', hombres: 68, mujeres: 70, alumnos: 138, grupos: 6, maestros: 10, administrativos: 3, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'PES', dsr: '1' },
  { region: 'AMECAMECA', valle: 'MEXICO', municipio: 'VALLE DE CHALCO SOLIDARIDAD', subsistema: 'FEDERALIZADO', control: 'PARTICULAR', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL PARTICULAR', cct: '15PES1384Z', turno: 'MATUTINO', nombre: 'SEBASTIAN LERDO DE TEJADA', domicilio: 'AVENIDA CUÍTLAHUAC', localidad: 'XICO', telefono: '155725184', zonaEscolar: '22', sector: '9', director: 'MIRIAM LOPEZ ESPINOSA', hombres: 22, mujeres: 17, alumnos: 39, grupos: 3, maestros: 7, administrativos: 3, aulasExistentes: 3, aulasEnUso: 3, modalidad: 'PES', dsr: '1' },

  // ATLACOMULCO
  { region: 'ATLACOMULCO', valle: 'TOLUCA', municipio: 'ACAMBAY DE RUIZ CASTAÑEDA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0240R', turno: 'MATUTINO', nombre: 'JUSTO SIERRA MENDEZ', domicilio: 'CALLE BENITO JUAREZ', localidad: 'VILLA DE ACAMBAY DE RUIZ CASTAÑEDA', telefono: '7181272023', zonaEscolar: '35', sector: '8', director: 'PEDRO VALENTE VALENCIA', hombres: 143, mujeres: 125, alumnos: 268, grupos: 9, maestros: 13, administrativos: 7, aulasExistentes: 12, aulasEnUso: 9, modalidad: 'DES', dsr: '4' },
  { region: 'ATLACOMULCO', valle: 'TOLUCA', municipio: 'ACAMBAY DE RUIZ CASTAÑEDA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0241Q', turno: 'MATUTINO', nombre: '5 DE FEBRERO', domicilio: 'TERRACERÍA DE SAN PEDRO DE LOS METATES', localidad: 'SAN PEDRO DE LOS METATES', telefono: '7121337295', zonaEscolar: '35', sector: '8', director: 'PEDRO MENDOZA LOPEZ', hombres: 42, mujeres: 59, alumnos: 101, grupos: 6, maestros: 9, administrativos: 7, aulasExistentes: 6, aulasEnUso: 6, modalidad: 'DES', dsr: '4' },
  { region: 'ATLACOMULCO', valle: 'TOLUCA', municipio: 'ACAMBAY DE RUIZ CASTAÑEDA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0010R', turno: 'MATUTINO', nombre: 'GUILLERMO GONZALEZ CAMARENA', domicilio: 'PROLONGACIÓN KILOMETRO 3.5 CARRETERA ACAMBAY BOCTO', localidad: 'VILLA DE ACAMBAY DE RUIZ CASTAÑEDA', telefono: '', zonaEscolar: '28', sector: '3', director: 'CRISTINA LETICIA BURGOS CORONA', hombres: 355, mujeres: 333, alumnos: 688, grupos: 15, maestros: 24, administrativos: 22, aulasExistentes: 17, aulasEnUso: 15, modalidad: 'DST', dsr: '4' },
  { region: 'ATLACOMULCO', valle: 'TOLUCA', municipio: 'ACULCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0099K', turno: 'MATUTINO', nombre: 'MELCHOR OCAMPO', domicilio: 'CARRETERA ESTATAL LIBRE ARROYO ZARCO', localidad: 'ARROYO ZARCO EJIDO', telefono: '', zonaEscolar: '28', sector: '3', director: 'HUGO MALDONADO RAMIREZ', hombres: 180, mujeres: 178, alumnos: 358, grupos: 9, maestros: 14, administrativos: 12, aulasExistentes: 9, aulasEnUso: 9, modalidad: 'DST', dsr: '4' },
  { region: 'ATLACOMULCO', valle: 'TOLUCA', municipio: 'ATLACOMULCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0001R', turno: 'MATUTINO', nombre: 'LIC. ISIDRO FABELA', domicilio: 'CALLE JUAN N. RESENDIZ 1', localidad: 'ATLACOMULCO DE FABELA', telefono: '7121220189', zonaEscolar: '30', sector: '8', director: 'MIGUEL SALAZAR MARTINEZ', hombres: 378, mujeres: 399, alumnos: 777, grupos: 18, maestros: 24, administrativos: 17, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '4' },

  // CHIMALHUACÁN
  { region: 'CHIMALHUACÁN', valle: 'MEXICO', municipio: 'CHICOLOAPAN', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0129O', turno: 'MATUTINO', nombre: 'PEDRO SAINZ DE BARANDA', domicilio: 'CALLE ALLENDE', localidad: 'CHICOLOAPAN DE JUAREZ', telefono: '5592331986', zonaEscolar: '21', sector: '8', director: 'ASUNCION RAMIREZ ALMORA', hombres: 500, mujeres: 527, alumnos: 1027, grupos: 22, maestros: 25, administrativos: 45, aulasExistentes: 25, aulasEnUso: 22, modalidad: 'DST', dsr: '1' },
  { region: 'CHIMALHUACÁN', valle: 'MEXICO', municipio: 'CHIMALHUACAN', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0245M', turno: 'MATUTINO', nombre: 'FELIPE CARRILLO PUERTO', domicilio: 'PROLONGACIÓN CHIMALHUACAN', localidad: 'CHIMALHUACAN', telefono: '5592017613', zonaEscolar: '20', sector: '5', director: 'EDGAR ALONSO ESTEVEZ', hombres: 299, mujeres: 310, alumnos: 609, grupos: 15, maestros: 20, administrativos: 15, aulasExistentes: 20, aulasEnUso: 15, modalidad: 'DES', dsr: '1' },

  // CUAUTITLÁN IZCALLI
  { region: 'CUAUTITLÁN IZCALLI', valle: 'MEXICO', municipio: 'ATIZAPAN DE ZARAGOZA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0008K', turno: 'MATUTINO', nombre: 'LIC. ISIDRO FABELA', domicilio: 'CALZADA SAN MATEO 15', localidad: 'CIUDAD LOPEZ MATEOS', telefono: '5527294940', zonaEscolar: '9', sector: '2', director: 'VICTOR ALFONSO ESPINOSA GARCIA', hombres: 376, mujeres: 423, alumnos: 799, grupos: 18, maestros: 19, administrativos: 14, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },
  { region: 'CUAUTITLÁN IZCALLI', valle: 'MEXICO', municipio: 'NICOLAS ROMERO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0005N', turno: 'MATUTINO', nombre: 'HIMNO NACIONAL', domicilio: 'PROLONGACIÓN 20 DE NOVIEMBRE', localidad: 'CIUDAD NICOLAS ROMERO', telefono: '5590170388', zonaEscolar: '8', sector: '2', director: 'MARIA MAGDALENA JUAREZ BALDERAS', hombres: 433, mujeres: 495, alumnos: 928, grupos: 18, maestros: 24, administrativos: 18, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },
  { region: 'CUAUTITLÁN IZCALLI', valle: 'MEXICO', municipio: 'CUAUTITLAN IZCALLI', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0021E', turno: 'MATUTINO', nombre: 'JOSE MARIA VELASCO', domicilio: 'AVENIDA CARRETERA LAGO DE GUADALUPE', localidad: 'CUAUTITLAN IZCALLI', telefono: '5558937740', zonaEscolar: '10', sector: '3', director: 'JUAN MANUEL MORFIN NAVARRO', hombres: 384, mujeres: 384, alumnos: 768, grupos: 18, maestros: 20, administrativos: 18, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },

  // ECATEPEC
  { region: 'ECATEPEC DE MORELOS', valle: 'MEXICO', municipio: 'ECATEPEC DE MORELOS', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0025A', turno: 'MATUTINO', nombre: 'LAZARO CARDENAS', domicilio: 'AVENIDA CIRCUNVALACIÓN SUR', localidad: 'ECATEPEC DE MORELOS', telefono: '5590808448', zonaEscolar: '16', sector: '4', director: 'IXHEL ARTEAGA FIGUEROA', hombres: 293, mujeres: 270, alumnos: 563, grupos: 18, maestros: 15, administrativos: 20, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '2' },
  { region: 'ECATEPEC DE MORELOS', valle: 'MEXICO', municipio: 'TECAMAC', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0039D', turno: 'MATUTINO', nombre: 'FELIPE VILLANUEVA', domicilio: 'CALLE CIRUELO', localidad: 'OJO DE AGUA', telefono: '5590748824', zonaEscolar: '32', sector: '4', director: 'MARIA ISABEL ISLAS SOLIS', hombres: 404, mujeres: 380, alumnos: 784, grupos: 18, maestros: 21, administrativos: 17, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '2' },

  // IXTLAHUACA
  { region: 'IXTLAHUACA', valle: 'TOLUCA', municipio: 'ALMOLOYA DE JUAREZ', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0105M', turno: 'MATUTINO', nombre: 'ALFREDO DEL MAZO VELEZ', domicilio: 'CALZADA DE LOS PINOS', localidad: 'SANTIAGUITO TLALCILALCALLI', telefono: '7251058336', zonaEscolar: '26', sector: '6', director: 'EPIFANIA GOMEZ GARCIA', hombres: 212, mujeres: 198, alumnos: 410, grupos: 12, maestros: 17, administrativos: 17, aulasExistentes: 12, aulasEnUso: 12, modalidad: 'DES', dsr: '4' },
  { region: 'IXTLAHUACA', valle: 'TOLUCA', municipio: 'IXTLAHUACA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0248J', turno: 'MATUTINO', nombre: 'VICENTE GUERRERO SALDAÑA', domicilio: 'CALLE VICENTE GUERRERO', localidad: 'IXTLAHUACA DE RAYON', telefono: '7224356682', zonaEscolar: '29', sector: '8', director: 'LETICIA LÓPEZ RAMOS', hombres: 410, mujeres: 403, alumnos: 813, grupos: 19, maestros: 32, administrativos: 13, aulasExistentes: 19, aulasEnUso: 19, modalidad: 'DES', dsr: '4' },

  // LERMA
  { region: 'LERMA', valle: 'TOLUCA', municipio: 'LERMA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0079E', turno: 'MATUTINO', nombre: 'PROFR. RAFAEL RAMIREZ', domicilio: 'AVENIDA HIDALGO 1', localidad: 'SAN MIGUEL AMEYALCO', telefono: '', zonaEscolar: '38', sector: '6', director: 'JOSE LUIS MEDINA SANDOVAL', hombres: 332, mujeres: 354, alumnos: 686, grupos: 18, maestros: 22, administrativos: 13, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '4' },
  { region: 'LERMA', valle: 'TOLUCA', municipio: 'TIANGUISTENCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0001J', turno: 'MATUTINO', nombre: 'ANDRES ALVARO GARCIA', domicilio: 'AVENIDA LIC. BENITO JUÁREZ 401', localidad: 'SANTIAGO TIANGUISTENCO DE GALEANA', telefono: '7131352270', zonaEscolar: '2', sector: '2', director: 'FEDERICO CARRETO ROMERO', hombres: 445, mujeres: 440, alumnos: 885, grupos: 18, maestros: 29, administrativos: 24, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '4' },

  // METEPEC
  { region: 'METEPEC', valle: 'TOLUCA', municipio: 'METEPEC', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0104N', turno: 'MATUTINO', nombre: 'ANDRES MOLINA ENRIQUEZ', domicilio: 'PROLONGACIÓN CAMINO A OCOTITLAN S/N', localidad: 'METEPEC', telefono: '7229379972', zonaEscolar: '34', sector: '7', director: 'FREDERIC JAIME REYES RODRIGUEZ', hombres: 193, mujeres: 169, alumnos: 362, grupos: 15, maestros: 20, administrativos: 26, aulasExistentes: 15, aulasEnUso: 15, modalidad: 'DES', dsr: '4' },
  { region: 'METEPEC', valle: 'TOLUCA', municipio: 'SAN MATEO ATENCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0079X', turno: 'MATUTINO', nombre: 'ISIDRO FABELA', domicilio: 'AVENIDA CHAPULTEPEC 15', localidad: 'SAN MATEO ATENCO', telefono: '7226826946', zonaEscolar: '3', sector: '2', director: 'ISRAEL AVILES GONZALEZ', hombres: 548, mujeres: 574, alumnos: 1122, grupos: 24, maestros: 34, administrativos: 22, aulasExistentes: 24, aulasEnUso: 24, modalidad: 'DST', dsr: '4' },

  // NAUCALPAN
  { region: 'NAUCALPAN', valle: 'TOLUCA', municipio: 'HUIXQUILUCAN', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0312U', turno: 'MATUTINO', nombre: 'DR. ANGEL MARIA GARIBAY KINTANA', domicilio: 'AVENIDA LUIS MANUEL ROJAS', localidad: 'HUIXQUILUCAN DE DEGOLLADO', telefono: '', zonaEscolar: '38', sector: '6', director: 'MERCED DALIA BERNARDINO MARTINEZ', hombres: 229, mujeres: 208, alumnos: 437, grupos: 11, maestros: 14, administrativos: 4, aulasExistentes: 13, aulasEnUso: 11, modalidad: 'DES', dsr: '4' },
  { region: 'NAUCALPAN', valle: 'MEXICO', municipio: 'NAUCALPAN DE JUAREZ', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0011Y', turno: 'MATUTINO', nombre: 'LIC. BENITO JUAREZ', domicilio: 'CALLE REFORMA 93', localidad: 'NAUCALPAN DE JUAREZ', telefono: '5555602520', zonaEscolar: '1', sector: '1', director: 'VIRGILIO HECTOR CORTES LOPEZ', hombres: 364, mujeres: 357, alumnos: 721, grupos: 18, maestros: 26, administrativos: 14, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },

  // NEZAHUALCÓYOTL
  { region: 'NEZAHUALCÓYOTL', valle: 'MEXICO', municipio: 'NEZAHUALCOYOTL', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0010Z', turno: 'MATUTINO', nombre: 'XICOTENCATL', domicilio: 'CALLE LAGO XOCHIMILCO', localidad: 'CIUDAD NEZAHUALCOYOTL', telefono: '5543393844', zonaEscolar: '33', sector: '5', director: 'BERTIN LOPEZ CABRERA', hombres: 211, mujeres: 232, alumnos: 443, grupos: 20, maestros: 27, administrativos: 23, aulasExistentes: 20, aulasEnUso: 20, modalidad: 'DES', dsr: '1' },

  // OTUMBA
  { region: 'OTUMBA', valle: 'MEXICO', municipio: 'ACOLMAN', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0115T', turno: 'MATUTINO', nombre: 'REVOLUCION MEXICANA', domicilio: 'PRIVADA 2DA PRIVADA DE LA AVENIDA MEXICO', localidad: 'SAN MIGUEL XOMETLA', telefono: '5520676868', zonaEscolar: '44', sector: '4', director: 'GUSTAVO JUSTINO AVILA OCAMPO', hombres: 265, mujeres: 285, alumnos: 550, grupos: 12, maestros: 19, administrativos: 19, aulasExistentes: 13, aulasEnUso: 12, modalidad: 'DES', dsr: '2' },

  // TEJUPILCO
  { region: 'TEJUPILCO', valle: 'TOLUCA', municipio: 'TEJUPILCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0008C', turno: 'MATUTINO', nombre: 'IGNACIO MANUEL ALTAMIRANO', domicilio: 'AVENIDA CRISTOBAL HIDALGO 6', localidad: 'TEJUPILCO DE HIDALGO', telefono: '7242672387', zonaEscolar: '9', sector: '1', director: 'ERIC RAFAEL RAMIREZ HURTADO', hombres: 144, mujeres: 141, alumnos: 285, grupos: 15, maestros: 24, administrativos: 23, aulasExistentes: 15, aulasEnUso: 15, modalidad: 'DST', dsr: '4' },

  // TENANCINGO
  { region: 'TENANCINGO', valle: 'TOLUCA', municipio: 'TENANCINGO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0077Z', turno: 'MATUTINO', nombre: 'LIC. JOSE VASCONCELOS', domicilio: 'AVENIDA 13 DE SEPTIEMBRE', localidad: 'LA CIENEGA', telefono: '7141421668', zonaEscolar: '24', sector: '2', director: 'MARILU DIAZ VALLE', hombres: 298, mujeres: 276, alumnos: 574, grupos: 18, maestros: 27, administrativos: 25, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DST', dsr: '4' },

  // TEPOTZOTLÁN
  { region: 'TEPOTZOTLÁN', mexico: 'MEXICO', municipio: 'TEPOTZOTLAN', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0020F', turno: 'MATUTINO', nombre: 'RAFAEL RAMIREZ', domicilio: 'CALLE MARGARITA MAZA DE JUÁREZ', localidad: 'TEPOTZOTLAN', telefono: '5611254733', zonaEscolar: '11', sector: '3', director: 'VICTOR BONIFACIO GONZALEZ MENDOZA', hombres: 308, mujeres: 343, alumnos: 651, grupos: 18, maestros: 24, administrativos: 17, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },

  // TEXCOCO
  { region: 'TEXCOCO', valle: 'MEXICO', municipio: 'TEXCOCO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0002Q', turno: 'MATUTINO', nombre: 'IGNACIO RAMIREZ', domicilio: 'CALLE EMILIANO ZAPATA', localidad: 'TEXCOCO DE MORA', telefono: '5909557990', zonaEscolar: '24', sector: '9', director: 'NICOLAS JAIMES MONTERO', hombres: 559, mujeres: 577, alumnos: 1136, grupos: 21, maestros: 26, administrativos: 20, aulasExistentes: 21, aulasEnUso: 21, modalidad: 'DES', dsr: '1' },

  // TLALNEPANTLA
  { region: 'TLALNEPANTLA', valle: 'MEXICO', municipio: 'TLALNEPANTLA DE BAZ', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0003P', turno: 'MATUTINO', nombre: 'NIÑOS HEROES', domicilio: 'CALLE DOCTOR GUSTAVO BAZ 4000', localidad: 'TLALNEPANTLA', telefono: '5553173295', zonaEscolar: '6', sector: '2', director: 'YURI ENRIQUE CERVANTES GOMEZ', hombres: 388, mujeres: 426, alumnos: 814, grupos: 18, maestros: 23, administrativos: 18, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '3' },

  // TOLUCA
  { region: 'TOLUCA', valle: 'TOLUCA', municipio: 'TOLUCA', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA TECNICA', cct: '15DST0002I', turno: 'MATUTINO', nombre: 'TIERRA Y LIBERTAD', domicilio: 'AVENIDA MIGUEL HIDALGO Y COSTILLA 100', localidad: 'TOLUCA DE LERDO', telefono: '7222149244', zonaEscolar: '1', sector: '1', director: 'OSCAR ZENEN SALGADO CID', hombres: 464, mujeres: 440, alumnos: 904, grupos: 24, maestros: 42, administrativos: 40, aulasExistentes: 24, aulasEnUso: 24, modalidad: 'DST', dsr: '4' },

  // TULTITLÁN
  { region: 'TULTITLÁN', valle: 'MEXICO', municipio: 'COACALCO DE BERRIOZABAL', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0286M', turno: 'MATUTINO', nombre: 'EMILIANO ZAPATA SALAZAR', domicilio: 'AVENIDA JUANA MA. PAVON', localidad: 'SAN FRANCISCO COACALCO', telefono: '5589466731', zonaEscolar: '14', sector: '4', director: 'GABRIEL APOLO DOMINGUEZ NARVAEZ', hombres: 314, mujeres: 352, alumnos: 666, grupos: 18, maestros: 23, administrativos: 14, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '2' },

  // VALLE DE BRAVO
  { region: 'VALLE DE BRAVO', valle: 'TOLUCA', municipio: 'VALLE DE BRAVO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0006M', turno: 'MATUTINO', nombre: 'JUAN A. MATEOS', domicilio: 'CALLE VERGEL 313', localidad: 'VALLE DE BRAVO', telefono: '', zonaEscolar: '28', sector: '7', director: 'DANIEL MENDOZA LOPEZ', hombres: 271, mujeres: 254, alumnos: 525, grupos: 18, maestros: 25, administrativos: 15, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '4' },

  // ZUMPANGO
  { region: 'ZUMPANGO', valle: 'MEXICO', municipio: 'ZUMPANGO', subsistema: 'FEDERALIZADO', control: 'OFICIAL', nivel: 'SECUNDARIA', servicioEducativo: 'SECUNDARIA GENERAL', cct: '15DES0260E', turno: 'MATUTINO', nombre: 'ROSARIO CASTELLANOS', domicilio: 'CALLE CARRETERA A CUAUTITLAN ESQUINA MIGUEL HIDALGO S/N', localidad: 'ZUMPANGO DE OCAMPO', telefono: '5911054928', zonaEscolar: '43', sector: '3', director: 'MARCO ANTONIO RIVERA GOMEZ', hombres: 284, mujeres: 281, alumnos: 565, grupos: 18, maestros: 21, administrativos: 11, aulasExistentes: 18, aulasEnUso: 18, modalidad: 'DES', dsr: '2' }
];
